apiVersion: v2
name: kube-router
description: A turnkey solution for Kubernetes networking with aim to provide operational simplicity and high performance.
type: application
version: 1.4.2
appVersion: v1.2.2

icon: https://cdn.rawgit.com/cloudnativelabs/kube-router/64f7700e/Documentation/img/logo-full.svg
home: https://www.kube-router.io/
sources:
  - https://github.com/enix/helm-charts/tree/master/charts/kube-router
  - https://github.com/cloudnativelabs/kube-router
maintainers:
  - name: Enix
    email: contact@enix.fr
    url: https://github.com/enixsas
  - name: Antoine Millet
    email: antoine@inaps.org
    url: https://github.com/NaPs
  - name: Alexandre Buisine
    email: alexandre.buisine@enix.fr
    url: https://github.com/abuisine