# Default values for cnpg-cluster.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# -- Number of Postgres instances in the cluster
replicaCount: 1

image:
  # -- Postgres image repository. Keep empty to use operator's default image. See: https://cloudnative-pg.io/documentation/1.17/operator_capability_levels/#override-of-operand-images-through-the-crd
  repository: "ghcr.io/cloudnative-pg/postgresql"
  # -- Postgres image pull policy
  pullPolicy: IfNotPresent
  # -- Override the Postgres image tag
  tag: ""

# -- Docker-registry secret names as an array
imagePullSecrets: []
# -- Create a docker-registry secret and use it as imagePullSecrets
registryCredentials:
# Eg:
#   mygitlab:
#     registry: gitlab-registry.example.org
#     email: foo@example.org
#     username: foobar
#     password: secret
# -- String to partially override cnpg-cluster.fullname template with a string (will prepend the release name)
nameOverride: ""
# --  String to fully override cnpg-cluster.fullname template with a string
fullnameOverride: ""

# -- CPU/Memory resource requests/limits
resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# -- Postgres instances labels for pod assignment
nodeSelector: {}

# -- Postgres instances labels for tolerations pod assignment
tolerations: []

# -- Extra configuration for Cluster's affinity resource,
# see: https://cloudnative-pg.io/documentation/1.17/api_reference/#AffinityConfiguration
extraAffinity: {}

persistence:
  # -- Size of each instance storage volume
  size: 1Gi
  # -- Resize existent PVCs, defaults to true	
  resizeInUseVolumes:
  # persistence.storageClass -- StorageClass to use for database data,
  # Applied after evaluating the PVC template, if available.
  # If not specified, generated PVCs will be satisfied by the default storage class
  storageClass: ""
  # persistence.pvcTemplate -- Template to be used to generate the Persistent Volume Claim
  pvcTemplate: {}

backup:
  # -- Enable backups
  enabled: false

  # -- The path where to store the backup (i.e. s3://bucket/path/to/folder) this path,
  # with different destination folders, will be used for WALs and for data --
  destinationPath: ""

  # -- RetentionPolicy is the retention policy to be used for backups and WALs (i.e. '60d').
  # The retention policy is expressed in the form of XXu where XX is a positive integer and
  # u is in [dwm] - days, weeks, months.
  retentionPolicy: 30d

  # -- (string) Endpoint to be used to upload data to the cloud, overriding the automatic endpoint discovery
  endpointURL:

  # -- (string) EndpointCA store the CA bundle of the barman endpoint. Useful when using self-signed
  # certificates to avoid errors with certificate issuer and barman-cloud-wal-archive
  endpointCA:

  # -- (string) The server name on S3, the cluster name is used if this parameter is omitted
  serverName:

  # -- Configuration of the backup of the WAL stream
  # See: https://cloudnative-pg.io/documentation/1.17/api_reference/#walbackupconfiguration
  wal: {}

  # -- Configuration of the backup of the data directory
  # See: https://cloudnative-pg.io/documentation/1.17/api_reference/#DataBackupConfiguration
  data: {}

  # -- Tags is a list of key value pairs that will be passed to the Barman --tags option
  tags: {}

  # -- HistoryTags is a list of key value pairs that will be passed to the Barman --history-tags option
  historyTags: {}

  # -- Override secret name for the backup credentials
  secretName: 

  # -- Enable the secret creation for the backup credentials
  createSecret: false

  # -- (object) The credentials to use to upload data to Google Cloud Storage
  # See: https://cloudnative-pg.io/documentation/1.17/api_reference/#GoogleCredentials
  googleCredentials:
    #gkeEnvironment:
    #applicationCredentials:

  # -- (object) The credentials to use to upload data to S3
  # See: https://cloudnative-pg.io/documentation/1.17/api_reference/#S3Credentials
  s3Credentials:
    # accessKeyId:
    # secretAccessKey:
    # region:
    # sessionToken:
    # inheritFromIAMRole:

  # -- (object) The credentials to use to upload data to Azure Blob Storage
  # See: https://cloudnative-pg.io/documentation/1.17/api_reference/#AzureCredentials
  azureCredentials:
    # connectionString:
    # storageAccount:
    # storageKey:
    # storageSasToken:
    # inheritFromAzureAD:

# -- Extra configuration for Cluster resource.
# See: https://cloudnative-pg.io/documentation/1.17/api_reference/#clusterspec
clusterExtraSpec: {}

# -- ScheduledBackup resources to create for this Cluster resource
# See: https://cloudnative-pg.io/documentation/1.17/api_reference/#ScheduledBackupSpec
scheduledBackups: {}
# Eg:
#   daily:
#     schedule: "0 0 0 * * *"

# -- Poller resources to create for this Cluster resource
# See: https://cloudnative-pg.io/documentation/1.17/api_reference/#PoolerSpec
poolers: {}
# Eg:
#   rw:
#     instances: 3
#     type: rw
#     pgbouncer:
#       poolMode: session
#       parameters:
#         max_client_conn: "1000"
#         default_pool_size: "10"