apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "network-exporter.fullname" . }}-config
  labels:
    {{- include "network-exporter.labels" . | nindent 4 }}
data:
  network_exporter.yml: |
    {{- .Values.networkExporterConfig | nindent 4 }}