{{- if .Values.enableHostDiscovery -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "network-exporter.fullname" . }}-node-reader
  labels:
    {{- include "network-exporter.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "network-exporter.fullname" . }}-node-reader
  labels:
    {{- include "network-exporter.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "network-exporter.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "network-exporter.fullname" . }}-node-reader
  apiGroup: rbac.authorization.k8s.io
{{- end -}}