{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "network-exporter.fullname" . }}
  labels:
    {{- include "network-exporter.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "network-exporter.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: /metrics
{{- end }}