# Default values for dothill-csi.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# -- Path to kubelet
kubeletPath: /var/lib/kubelet
# -- Wether psp admission controller has been enabled in the cluster or not
pspAdmissionControllerEnabled: false

image:
  # -- Docker repository to use for nodes and controller
  repository: docker.io/enix/dothill-csi
  # -- Tag to use for nodes and controller
  # @default -- The chart will use the appVersion value by default if not given.
  tag: ""

# -- Controller sidecar for provisionning
csiProvisioner:
  image:
    repository: k8s.gcr.io/sig-storage/csi-provisioner
    tag: v2.1.0
  # -- Timeout for gRPC calls from the csi-provisioner to the controller
  timeout: 30s
  # -- Extra arguments for csi-provisioner controller sidecar
  extraArgs: []

# -- Controller sidecar for attachment handling
csiAttacher:
  image:
    repository: k8s.gcr.io/sig-storage/csi-attacher
    tag: v2.2.1
  # -- Timeout for gRPC calls from the csi-attacher to the controller
  timeout: 30s
  # -- Extra arguments for csi-attacher controller sidecar
  extraArgs: []

# -- Controller sidecar for volume expansion
csiResizer:
  image:
    repository: k8s.gcr.io/sig-storage/csi-resizer
    tag: v1.1.0
  # -- Extra arguments for csi-resizer controller sidecar
  extraArgs: []

# -- Controller sidecar for snapshots handling
csiSnapshotter:
  image:
    repository: k8s.gcr.io/sig-storage/csi-snapshotter
    tag: v4.0.0
  # -- Extra arguments for csi-snapshotter controller sidecar
  extraArgs: []

# -- Node sidecar for plugin registration
csiNodeRegistrar:
  image:
    repository: k8s.gcr.io/sig-storage/csi-node-driver-registrar
    tag: v2.1.0
  # -- Extra arguments for csi-node-registrar node sidecar
  extraArgs: []

controller:
  # -- Extra arguments for dothill-controller container
  extraArgs: []

node:
  # -- Extra arguments for dothill-node containers
  extraArgs: []

multipathd:
  # -- Extra arguments for multipathd containers
  extraArgs: []

# -- Container that convert CSI liveness probe to kubernetes liveness/readiness probe
nodeLivenessProbe:
  image:
    repository: quay.io/k8scsi/livenessprobe
    tag: v2.2.0
  # -- Extra arguments for the node's liveness probe containers
  extraArgs: []

nodeServer:
  # -- Kubernetes nodeSelector field for dothill-node-server Pod
  nodeSelector:
  # -- Kubernetes nodeAffinity field for dothill-node-server Pod
  nodeAffinity:

podMonitor:
  # -- Set a Prometheus operator PodMonitor ressource (true or false)
  enabled: false

serviceMonitor:
  # -- Set a Prometheus operator ServiceMonitor ressource (true or false)
  enabled: false
  